apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cron-template
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: cron-pipeline
        params:
        - name: apikey
          value: $(params.apikey)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cron-binding
spec:
  params:
    - name: repository
      value: "https://github.ibm.com/test-rig/gitsecure-pipeline"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron-listener
spec:
  triggers:
    - binding:
        name: cron-binding
      template:
        name: cron-template
