apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
  tasks:
    - name: pipeline-gitsecure-vpatrol-task
      taskRef:
        name: gitsecure-vpatrol-task
      params:
        - name: apikey
          value: $(params.apikey)
