apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: revision
      description: The git repo revision
    - name: prnumber
      description: The pullrequest number
    - name: apikey
      description: the ibmcloud api key
    - name: imageurl
      description: image url into registry
  tasks:
    - name: pipeline-gitsecure-vpatrol-task
      taskRef:
        name: gitsecure-vpatrol-task
      params:
        - name: apikey
          value: $(params.apikey)
