apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: apikey
      description: the ibmcloud api key
  tasks:
    - name: pipeline-gitsecure-vpatrol
      taskRef:
        name: gitsecure-discovery-vpatrol
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: apikey
          value: $(params.apikey)
