apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-discovery-vpatrol
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: vulnerability-patroling
      image: shri4u/rig-vpatrol:test
      imagePullPolicy: Always
      command:
        - /gitsecure/vpatrol
      args:
        - "-apikey"
        -  $(inputs.params.apikey)
        - "-frequency"
        - "1"
        - "-rigserviceapi"
        - "http://169.47.180.148:30950"
        - "-saapi"
        - "http://169.47.180.157:30940"
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
