apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-discovery-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: clone-repo
      image: shri4u/git-cloner
      imagePullPolicy: Always
      command: ["/gitsecure/git-cloner"]
      args:
        - "-apikey"
        - "$(inputs.params.apikey)"
        - "-giturl"
        - "$(inputs.params.repository)"
        - "-gitbranch"
        - "$(inputs.params.revision)"
        - "-dir"
        - "."
    - name: discovery
      image: shri4u/rig:rc1
      imagePullPolicy: Always
      command:
        - /go/src/github.ibm.com/rig/rig-app
      args:
        - "-giturl"
        -  $(inputs.params.repository)
        - "-gitbranch"
        -  $(inputs.params.revision)
        - "-repodir"
        -  "/workspace"
        - "-dburl"
        - "bolt://169.47.180.157:30687"
        - "-clairapi"
        - "http://169.47.180.148:30890"
        - "-pysafetyapi"
        - "http://169.47.180.157:30892"
        - "-pedigreeapi"
        - "http://169.62.50.203:9940"
        - "-rigapi"
        - "http://169.47.180.148:30950"
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-remediation-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: prnumber
        description: the git pr number
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: remediation
      image: shri4u/rigrec:vpatrol-test
      imagePullPolicy: Always
      command:
        - /go/src/github.ibm.com/rig-recommend/rig-recommend
      args:
        - "-giturl"
        -  $(inputs.params.repository)
        - "-gitbranch"
        -  $(inputs.params.revision)
        - "-repodir"
        - "/workspace"
        - "-rigserviceapi"
        - "http://169.47.180.148:30950"
        - "-pr"
        - $(inputs.params.prnumber)
        - "-apikey"
        - $(inputs.params.apikey)
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-cis-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: prnumber
        description: the git pr number
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: clone-repo
      image: shri4u/git-cloner
      imagePullPolicy: Always
      command: ["/gitsecure/git-cloner"]
      args:
        - "-apikey"
        - "$(inputs.params.apikey)"
        - "-giturl"
        - "$(inputs.params.repository)"
        - "-gitbranch"
        - "$(inputs.params.revision)"
        - "-dir"
        - "."
    - name: cis
      image: shri4u/cis-task:rc1
      imagePullPolicy: Always
      command:
        - /go/src/github.ibm.com/rig-cis-task/bin/cis-task
      args:
        - "-giturl"
        -  $(inputs.params.repository)
        - "-gitbranch"
        -  $(inputs.params.revision)
        - "-repodir"
        - "/workspace"
        - "-rigserviceapi"
        - "http://169.47.180.148:30950"
        - "-pr"
        - $(inputs.params.prnumber)
        - "-apikey"
        - $(inputs.params.apikey)
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-bom-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: prnumber
        description: the git pr number
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: bom
      image: shri4u/rig-bom:rc1
      imagePullPolicy: Always
      command:
        - /gitsecure/bom-task
      args:
        - "-giturl"
        -  $(inputs.params.repository)
        - "-gitbranch"
        -  $(inputs.params.revision)
        - "-rigserviceapi"
        - "http://169.47.180.148:30950"
        - "-pr"
        - $(inputs.params.prnumber)
        - "-apikey"
        - $(inputs.params.apikey)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-ossc-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: revision
        description: the revision
        default: master
      - name: repository
        description: the git repo
      - name: prnumber
        description: the git pr number
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: ossc
      image: cmadam/ossc-toolchain:rc1
      imagePullPolicy: Always
      command:
        - "python"
        - "/ossc/ossc.py"
      args:
        - "--giturl"
        -  $(inputs.params.repository)
        - "--gitbranch"
        -  $(inputs.params.revision)
        - "--rigserviceapi"
        - "http://169.47.180.148:30950"
        - "--pr"
        - $(inputs.params.prnumber)
        - "--apikey"
        - $(inputs.params.apikey)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-hadolint-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: prnumber
        description: the git pr number
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: clone-repo
      image: shri4u/git-cloner
      imagePullPolicy: Always
      command: ["/gitsecure/git-cloner"]
      args:
        - "-apikey"
        - "$(inputs.params.apikey)"
        - "-giturl"
        - "$(inputs.params.repository)"
        - "-gitbranch"
        - "$(inputs.params.revision)"
        - "-dir"
        - "."
    - name: hadolint
      image: shri4u/hadolint-task:rc1
      imagePullPolicy: Always
      command:
        - /gitsecure/hadolint-task
      args:
        - "-giturl"
        -  $(inputs.params.repository)
        - "-gitbranch"
        -  $(inputs.params.revision)
        - "-rigserviceapi"
        - "http://169.47.180.148:30950"
        - "-pr"
        - $(inputs.params.prnumber)
        - "-apikey"
        - $(inputs.params.apikey)
        - "-repodir"
        - "/workspace"
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-deployanalytics-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: prnumber
        description: the git pr number
      - name: apikey
        description: the ibmcloud api key
  steps:
    - name: clone-repo
      image: shri4u/git-cloner
      imagePullPolicy: Always
      command: ["/gitsecure/git-cloner"]
      args:
        - "-apikey"
        - "$(inputs.params.apikey)"
        - "-giturl"
        - "$(inputs.params.repository)"
        - "-gitbranch"
        - "$(inputs.params.revision)"
        - "-dir"
        - "."
    - name: deploy-analytics
      image: cmadam/deployment-checker:rc1
      imagePullPolicy: Always
      args:
        - "--giturl"
        -  $(inputs.params.repository)
        - "--gitbranch"
        -  $(inputs.params.revision)
        - "--rigserviceapi"
        - "http://169.47.180.148:30950"
        - "--pr"
        - $(inputs.params.prnumber)
        - "--apikey"
        - $(inputs.params.apikey)
        - "--repodir"
        - "/workspace"
        - "--clairapi"
        - "http://169.47.180.148:30890"
        - "--pedigreeapi"
        - "http://169.62.50.203:9940"
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)

---
apiVersion: v1
data:
  config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyaHlhVFIxT25CaGMzTjNNSEprIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4yIChsaW51eCkiCgl9Cn0K
kind: Secret
metadata:
  name: dockerhub-secret
type: Opaque
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: imageurl
        description: image url into registry
  steps:
    - name: clone-repo
      image: shri4u/git-cloner
      imagePullPolicy: Always
      command: ["/gitsecure/git-cloner"]
      args:
        - "-apikey"
        - "$(inputs.params.apikey)"
        - "-giturl"
        - "$(inputs.params.repository)"
        - "-gitbranch"
        - "$(inputs.params.revision)"
        - "-dir"
        - "."
    - name: image-build-and-push
      image: gcr.io/kaniko-project/executor:v0.13.0
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
      - /kaniko/executor
      args:
      - "--dockerfile=/workspace/Dockerfile"
      - "--destination=docker.io/shri4u/myapp-base:0.1"
      - "--context=/workspace"
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /builder/home/.docker/
          name: registry-secret
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: registry-secret
      secret:
        secretName: dockerhub-secret
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitsecure-buildindexer-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: imageurl
        description: image url into registry
  steps:
    - name: clone-repo
      image: shri4u/git-cloner
      imagePullPolicy: Always
      command: ["/gitsecure/git-cloner"]
      args:
        - "-apikey"
        - "$(inputs.params.apikey)"
        - "-giturl"
        - "$(inputs.params.repository)"
        - "-gitbranch"
        - "$(inputs.params.revision)"
        - "-dir"
        - "."
    - name: build-indexer
      image: shri4u/rig-imgbuilger
      imagePullPolicy: Always
      command:
        - /gitsecure/build-indexer
      args:
        - "-imageurl"
        -  "docker.io/shri4u/myapp-base:0.1"
        - "-rigserviceapi"
        - "http://169.47.180.148:30950"
        - "-repodir"
        - "/workspace"
        - "-giturl"
        -  $(inputs.params.repository)
        - "-gitbranch"
        -  $(inputs.params.revision)
        - "-dockerfile"
        - "/Dockerfile"
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
